### ISSUE TITLE
Need information about Home Depot API 

### ISSUE THREAD

**Issue by jyothimanchena** [homedepot/react-component-grid#15]
Hi homedepot team,

We need Home Depot API , this is for Public or Private ? We need to implement the product using home depot API but I tried to search home depot API ,  I got one official link but it is asking authentication how to get the API and authentication please clarity about API.

Thanks,
Suri

**Comment by whitneyw** [comment]
Hi Suri,

Unfortunately, Home Depot does not allow public access to company APIs at this time. Access to the product assortment and catalog is considered proprietary, and may contain trade secrets.

If you'd like to know more about open source projects built and maintained by developers at Home Depot, you can read the [Home Depot Guide to OSS](https://homedepot.github.io/opensource/).

**Comment by joebarrero** [comment]
Or not.  The Home Depot Guide to OSS leads to a big fat 404 error.

**Comment by whitneyw** [comment]
Hi Joe -- You're right! The Home Depot Guide to OSS is temporarily offline.
Feel free to check back later 🙂

**Comment by choward8** [comment]
Hi Whitney,
Is there a public facing API for product manufacturers? I saw that home depot did have an API at one point but I was sure if it still existed.
Thanks,
Cody

**Comment by whitneyw** [comment]
Hi Cody -- as I posted above, Home Depot does not grant public access to company APIs (including product manufacturers).

**Comment by choward8** [comment]
Ok, Thank you very much

**Comment by JackTG** [comment]
Hi Whitney,
How to access the APIs of Home Depot? What conditions are required?
Thanks,
Jack

**Comment by whitneyw** [comment]
Hi Jack,

As mentioned several times before in this thread, Home Depot does not allow public access to company APIs. Sorry!

**Comment by JackTG** [comment]
Is that mean the API is only available to home depot employees?

**Comment by whitneyw** [comment]
That's correct -- The Home Depot APIs are only available to The Home Depot employees.

**Comment by JackTG** [comment]
I got it. Thank you very much!🙂
