### ISSUE TITLE
Add module to NPM for reuse in projects.

### ISSUE THREAD

**Issue by adron-orange** [homedepot/react-component-grid#4]
@jonnyohjonnyo could you fork & submit a repo w/ > https://www.npmjs.com/ added and with the `npm install xyz` instructions in the README.md?

**Comment by adron-orange** [comment]
Project needs renamed for NPM. Ideas @jonnyohjonnyo & @thd-mesa?

**Comment by whitneyw** [comment]
This project is available on npm under the package name `react-flexbox-component-grid` ✅

**Comment by thd-mesa** [comment]
@whitneyw is correct! https://www.npmjs.com/package/react-flexbox-component-grid
